#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
TikTok Insight V1.2 - AI Enriched Comment Evidence Packet

Purpose:
- Read comment evidence packet generated by comment_evidence_packet.py
- Use OpenAI GPT to translate and classify liked comments
- Output enriched comment evidence packet for V1.2 comment-driven insight report

Usage:
  source .env.local
  python3 comment_evidence_ai_enrich.py ./reports/comment_evidence_xxx.json

Output:
  reports/comment_evidence_enriched_<stem>.json
  reports/comment_evidence_enriched_<stem>.md
"""

import json
import os
import sys
import re
from pathlib import Path
from datetime import datetime
from typing import Any, Dict, List

try:
    from openai import OpenAI
except ImportError:
    print("ERROR: openai package not installed. Try: pip3 install openai")
    sys.exit(1)


BASE_DIR = Path(__file__).resolve().parent
REPORTS_DIR = BASE_DIR / "reports"
REPORTS_DIR.mkdir(exist_ok=True)


MAX_COMMENTS_TO_ENRICH = 100


SYSTEM_PROMPT = """你是 TikTok Shop 评论区需求洞察分析员。

你的任务不是写完整报告，而是对每条 TikTok 评论做结构化处理。

你必须基于评论原文逐条输出：
1. 中文翻译
2. 评论类型
3. 暴露出的用户需求/疑虑
4. 对下一条素材的复刻价值
5. 是否值得用于下一条素材
6. 推荐素材打法

评论类型只能从以下类型中选择一个或两个，用“ / ”连接：
- 购买意向/购买方式
- 链接/价格询问
- 效果质疑
- 参数/规格问题
- 适用场景提问
- 人群/场景共鸣
- 价格/性价比质疑
- 使用门槛疑问
- 真实性/广告质疑
- 负面反馈
- 玩梗/低价值互动
- 正向口碑
- 季节/场景限制质疑
- 其他

判断规则：
- 如果评论是在问能不能用于某个设备/场景，优先归为“适用场景提问”或“参数/规格问题”。
- 如果评论是在质疑产品能不能带动大功率设备，归为“参数/规格问题 / 效果质疑”。
- 如果评论是在调侃、玩笑，但背后有产品能力质疑，也要指出潜在疑虑。
- 如果评论是简单夸赞，归为“正向口碑”。
- 如果评论只是表情、哈哈、无实质信息，归为“玩梗/低价值互动”。
- 不要凭空脑补评论没有表达的信息。
- 中文翻译要自然，方便中国团队阅读。
- 输出必须是严格 JSON，不要写 markdown，不要加解释。
"""


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def save_json(path: Path, data: Dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def md_escape(text: Any) -> str:
    return str(text or "").replace("\n", " ").replace("|", "｜").strip()


def extract_json_text(text: str) -> str:
    """
    OpenAI normally returns strict JSON, but this provides a fallback
    if the model wraps JSON in ```json fences.
    """
    text = text.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)

    start = text.find("{")
    end = text.rfind("}")

    if start != -1 and end != -1 and end > start:
        return text[start:end + 1]

    return text


def build_user_prompt(comments: List[Dict[str, Any]]) -> str:
    slim_comments = []

    for idx, c in enumerate(comments, 1):
        slim_comments.append({
            "rank": idx,
            "cid": c.get("cid", ""),
            "unique_id": c.get("unique_id", ""),
            "text": c.get("text", ""),
            "digg_count": c.get("digg_count", 0),
            "reply_count": c.get("reply_count", 0),
            "create_time_iso": c.get("create_time_iso", ""),
            "rule_based_comment_type": c.get("comment_type", ""),
            "rule_based_exposed_need": c.get("exposed_need", ""),
        })

    return f"""请对下面 TikTok 有点赞评论做逐条结构化增强。

要求：
- 保留 rank 和 cid
- 不要删除任何评论
- 每条评论都要输出中文翻译
- 每条评论都要判断评论类型、暴露需求/疑虑、复刻价值
- 如果是低价值评论，也要说明为什么低价值
- 输出必须是严格 JSON
- 不要输出 markdown
- 不要输出任何额外解释

输出 JSON 格式如下：
{{
  "items": [
    {{
      "rank": 1,
      "cid": "xxx",
      "original_text": "原评论",
      "translated_zh": "中文翻译",
      "comment_type": "评论类型",
      "exposed_need_or_objection": "暴露出的需求/疑虑",
      "replication_value": "高/中/低 + 原因",
      "worth_using_for_next_content": true,
      "recommended_content_angle": "下一条素材可以怎么用这个评论"
    }}
  ]
}}

评论列表：
{json.dumps(slim_comments, ensure_ascii=False, indent=2)}
"""


def call_openai_enrich(comments: List[Dict[str, Any]]) -> Dict[str, Any]:
    api_key = os.environ.get("OPENAI_API_KEY")
    model = os.environ.get("OPENAI_MODEL", "gpt-5.5")
    base_url = os.environ.get("OPENAI_BASE_URL", "").strip()

    if not api_key:
        raise RuntimeError("Missing OPENAI_API_KEY. Run: source .env.local")

    client_kwargs = {"api_key": api_key}
    if base_url:
        client_kwargs["base_url"] = base_url

    client = OpenAI(**client_kwargs)

    user_prompt = build_user_prompt(comments)

    print(f"Using model: {model}")
    print(f"Base URL: {base_url or 'OpenAI default'}")
    print(f"Comments to enrich: {len(comments)}")

    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ],
        max_completion_tokens=20000,
    )

    content = resp.choices[0].message.content or ""
    json_text = extract_json_text(content)

    try:
        parsed = json.loads(json_text)
    except Exception as e:
        debug_path = REPORTS_DIR / "comment_evidence_ai_enrich_bad_response.txt"
        debug_path.write_text(content, encoding="utf-8")
        raise RuntimeError(f"Failed to parse GPT JSON response: {e}. Raw response saved to {debug_path}")

    if not isinstance(parsed, dict) or not isinstance(parsed.get("items"), list):
        raise RuntimeError("GPT response JSON must be an object with items list.")

    return parsed


def merge_enrichment(packet: Dict[str, Any], enriched: Dict[str, Any]) -> Dict[str, Any]:
    all_liked = packet.get("all_liked_comments", [])

    enriched_by_cid = {}
    enriched_by_rank = {}

    for item in enriched.get("items", []):
        cid = str(item.get("cid") or "")
        rank = item.get("rank")
        if cid:
            enriched_by_cid[cid] = item
        if rank is not None:
            enriched_by_rank[int(rank)] = item

    merged_liked = []

    for idx, c in enumerate(all_liked, 1):
        cid = str(c.get("cid") or "")
        ai = enriched_by_cid.get(cid) or enriched_by_rank.get(idx) or {}

        merged = dict(c)
        merged["translated_zh"] = ai.get("translated_zh", "")
        merged["ai_comment_type"] = ai.get("comment_type", c.get("comment_type", ""))
        merged["ai_exposed_need_or_objection"] = ai.get(
            "exposed_need_or_objection",
            c.get("exposed_need", "")
        )
        merged["ai_replication_value"] = ai.get("replication_value", c.get("replication_value", ""))
        merged["worth_using_for_next_content"] = bool(ai.get("worth_using_for_next_content", False))
        merged["recommended_content_angle"] = ai.get("recommended_content_angle", "")

        merged_liked.append(merged)

    top_liked = merged_liked[:30]

    ai_type_counts: Dict[str, int] = {}
    useful_count = 0

    for c in merged_liked:
        t = c.get("ai_comment_type") or "其他"
        ai_type_counts[t] = ai_type_counts.get(t, 0) + 1
        if c.get("worth_using_for_next_content"):
            useful_count += 1

    new_packet = dict(packet)
    new_packet["packet_version"] = "TikTok Insight V1.2 comment_evidence_packet_ai_enriched_v0.2"
    new_packet["ai_enriched_at"] = datetime.utcnow().isoformat() + "Z"
    new_packet["ai_type_counts"] = ai_type_counts
    new_packet["useful_comment_count"] = useful_count
    new_packet["top_liked_comments"] = top_liked
    new_packet["all_liked_comments"] = merged_liked

    if "comment_summary" in new_packet:
        new_packet["comment_summary"]["useful_comment_count"] = useful_count
        new_packet["comment_summary"]["ai_enriched"] = True

    return new_packet


def render_markdown(packet: Dict[str, Any]) -> str:
    summary = packet.get("comment_summary", {})
    top = packet.get("top_liked_comments", [])
    all_liked = packet.get("all_liked_comments", [])

    lines = []
    lines.append("# TikTok Insight V1.2 评论证据包 AI 增强版")
    lines.append("")
    lines.append("## 1. 评论数据概览")
    lines.append("")
    lines.append(f"- 来源文件：`{packet.get('source_file', '')}`")
    lines.append(f"- 评论总数：{summary.get('total_comments', 0)}")
    lines.append(f"- 有点赞评论数：{summary.get('liked_comments', 0)}")
    lines.append(f"- 最高点赞数：{summary.get('top_comment_like_count', 0)}")
    lines.append(f"- 可用于下一条素材的评论数：{summary.get('useful_comment_count', packet.get('useful_comment_count', 0))}")
    lines.append(f"- 是否适合评论区需求洞察：{'是' if summary.get('effective_for_insight') else '否'}")
    lines.append("")
    lines.append("## 2. AI 评论类型统计")
    lines.append("")

    ai_counts = packet.get("ai_type_counts", {})
    if ai_counts:
        for k, v in sorted(ai_counts.items(), key=lambda x: x[1], reverse=True):
            lines.append(f"- {k}：{v}")
    else:
        lines.append("- 暂无统计")
    lines.append("")

    lines.append("## 3. 高赞评论证据表 Top 30")
    lines.append("")
    lines.append("| 排名 | 点赞数 | 回复数 | 用户 | 原评论 | 中文翻译 | AI评论类型 | 暴露需求/疑虑 | 复刻价值 | 下一条素材打法 |")
    lines.append("|---|---:|---:|---|---|---|---|---|---|---|")

    for i, c in enumerate(top, 1):
        lines.append(
            f"| {i} | {c.get('digg_count', 0)} | {c.get('reply_count', 0)} | "
            f"{md_escape(c.get('unique_id'))} | {md_escape(c.get('text'))} | "
            f"{md_escape(c.get('translated_zh'))} | {md_escape(c.get('ai_comment_type'))} | "
            f"{md_escape(c.get('ai_exposed_need_or_objection'))} | "
            f"{md_escape(c.get('ai_replication_value'))} | "
            f"{md_escape(c.get('recommended_content_angle'))} |"
        )

    lines.append("")
    lines.append("## 4. 所有有点赞评论 AI 汇总")
    lines.append("")
    lines.append("> 注：这里保留所有 diggCount > 0 的评论，避免 AI 只看摘要造成关键信息遗漏。")
    lines.append("")
    lines.append("| 排名 | 点赞数 | 原评论 | 中文翻译 | AI评论类型 | 暴露需求/疑虑 | 是否值得用于下一条素材 |")
    lines.append("|---|---:|---|---|---|---|---|")

    for i, c in enumerate(all_liked, 1):
        worth = "是" if c.get("worth_using_for_next_content") else "否"
        lines.append(
            f"| {i} | {c.get('digg_count', 0)} | {md_escape(c.get('text'))} | "
            f"{md_escape(c.get('translated_zh'))} | {md_escape(c.get('ai_comment_type'))} | "
            f"{md_escape(c.get('ai_exposed_need_or_objection'))} | {worth} |"
        )

    lines.append("")
    lines.append("## 5. 给 V1.2 洞察报告的使用说明")
    lines.append("")
    lines.append("后续 V1.2 评论洞察报告必须基于本证据包输出，不允许脱离评论事实凭空总结。")
    lines.append("所有用户需求、人群、场景、购买阻力判断，都应引用或对应上方评论证据。")
    lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) < 2:
        print("Usage: source .env.local && python3 comment_evidence_ai_enrich.py ./reports/comment_evidence_xxx.json")
        sys.exit(1)

    source_file = Path(sys.argv[1]).expanduser().resolve()

    if not source_file.exists():
        print(f"ERROR: file not found: {source_file}")
        sys.exit(1)

    packet = load_json(source_file)
    all_liked = packet.get("all_liked_comments", [])

    if not isinstance(all_liked, list):
        print("ERROR: packet missing all_liked_comments list")
        sys.exit(1)

    comments_to_enrich = all_liked[:MAX_COMMENTS_TO_ENRICH]

    if not comments_to_enrich:
        print("No liked comments to enrich.")
        sys.exit(0)

    enriched = call_openai_enrich(comments_to_enrich)
    new_packet = merge_enrichment(packet, enriched)

    stem = source_file.stem.replace("comment_evidence_", "")
    out_json = REPORTS_DIR / f"comment_evidence_enriched_{stem}.json"
    out_md = REPORTS_DIR / f"comment_evidence_enriched_{stem}.md"

    save_json(out_json, new_packet)
    out_md.write_text(render_markdown(new_packet), encoding="utf-8")

    summary = new_packet.get("comment_summary", {})

    print("✅ AI enriched comment evidence packet generated")
    print(f"source: {source_file}")
    print(f"comments: {summary.get('total_comments', 0)}")
    print(f"liked_comments: {summary.get('liked_comments', 0)}")
    print(f"useful_comment_count: {summary.get('useful_comment_count', 0)}")
    print(f"json: {out_json}")
    print(f"md: {out_md}")


if __name__ == "__main__":
    main()
